# Generated by Django 5.1.6 on 2025-03-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
    ]
